export const SET_AUTH = 'setUser'
export const PURGE_AUTH = 'logOut'
export const CHECK_AUTH = 'ckeckAuth'
export const SET_ERROR = 'setError'
export const PURGE_ERROR = 'purgeError'
export const SET_PROCESSING = 'setProcessing'
